--- Dockerfile
+++ Dockerfile
@@ -1,10 +1,10 @@
-#FROM heroku/ruby
+FROM heroku/ruby
 
-FROM ruby:2.2.5
-RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
-RUN mkdir /myapp
-WORKDIR /myapp
-ADD Gemfile /myapp/Gemfile
-ADD Gemfile.lock /myapp/Gemfile.lock
-RUN bundle install
-ADD . /myapp
\ No newline at end of file
+#FROM ruby:2.2.5
+#RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
+#RUN mkdir /myapp
+#WORKDIR /myapp
+#ADD Gemfile /myapp/Gemfile
+#ADD Gemfile.lock /myapp/Gemfile.lock
+#RUN bundle install
+#ADD . /myapp
\ No newline at end of file
