# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
cat = FieldCategory.create(:name => "Source", :order => 0)
Field.create(:name => "Page #", :display_type => "integer", :field_category => cat)
Field.create(:name => "URL", :display_type => "url", :field_category => cat)
cat = FieldCategory.create(:name => "Basic Info", :order => 1)
Field.create(:name => "Tone Set", :display_type => "string", :field_category => cat)
Field.create(:name => "Rhythm Set", :display_type => "rhythm", :field_category => cat)
Field.create(:name => "Comfortable Starting Pitch", :display_type => "string", :field_category => cat)
Field.create(:name => "Tonality (mode)", :display_type => "string", :field_category => cat)
Field.create(:name => "Level (AKI level for full analysis)", :display_type => "integer", :field_category => cat)
Field.create(:name => "Grade Levels", :display_type => "string", :field_category => cat)
Field.create(:name => "Tempo", :display_type => "string", :field_category => cat)
Field.create(:name => "Ethnic / Geographic Origin", :display_type => "string", :field_category => cat)
cat = FieldCategory.create(:name => "Form", :order => 2)
Field.create(:name => "Sectional Form", :display_type => "string", :field_category => cat)
Field.create(:name => "Form Features", :display_type => "string", :field_category => cat)
Field.create(:name => "Phrasal Form", :display_type => "string", :field_category => cat)
Field.create(:name => "Cadence Notes", :display_type => "string", :field_category => cat)
Field.create(:name => "Number of Bars", :display_type => "integer", :field_category => cat)
Field.create(:name => "Number of Verses", :display_type => "integer", :field_category => cat)
cat = FieldCategory.create(:name => "Harmony / Part Work", :order => 3)
Field.create(:name => "Part Work Type", :display_type => "string", :field_category => cat)
Field.create(:name => "Chords", :display_type => "string", :field_category => cat)
cat = FieldCategory.create(:name => "Expression & Style", :order => 4)
Field.create(:name => "Themes", :display_type => "string", :field_category => cat)
Field.create(:name => "Mood", :display_type => "string", :field_category => cat)
Field.create(:name => "Expression", :display_type => "string", :field_category => cat)
cat = FieldCategory.create(:name => "Pedagogy", :order => 5)
Field.create(:name => "Notation", :display_type => "string", :field_category => cat)
Field.create(:name => "Readability", :display_type => "string", :field_category => cat)
Field.create(:name => "Challenges", :display_type => "string", :field_category => cat)
Field.create(:name => "Pedagogical Use", :display_type => "string", :field_category => cat)
cat = FieldCategory.create(:name => "Related Activities", :order => 6)
Field.create(:name => "Formation", :display_type => "string", :field_category => cat)
Field.create(:name => "Props / Materials", :display_type => "string", :field_category => cat)
Field.create(:name => "Action", :display_type => "string", :field_category => cat)
Field.create(:name => "Direction", :display_type => "string", :field_category => cat)
